### ISSUE TITLE
No activation used in decoder #bug

### ISSUE THREAD

**Issue by alirezaomidi** [theislab/trVAE#8]
It seems there is a bug in the decoder: Except for the first layer (the MMD layer), no activation function is used for the layers.

https://github.com/theislab/trVAE/blob/d713be5333b4f0868bc772f31978405e0cedbe9d/trvae/models/_trvae.py#L154-L158

**Comment by Naghipourfar** [comment]
Hi Alireza, 

Thanks for reporting. LeakyReLU activations are being used in decoder's all layers now.
