### ISSUE TITLE
AttributeError: module 'trvae.models' has no attribute 'trVAE'

### ISSUE THREAD

**Issue by gauravj49** [theislab/trVAE#9]
Hi trVAE team,

I am using trVAE for batch correction. It was working fine until last month but I started to get the below error recently.

`AttributeError: module 'trvae.models' has no attribute 'trVAE'`

I can see that there are new classes but no class trVAE.  Could you please recommend which one I can use?

- CVAE
- trAE
- VAE
- MMDCVAE

module versions:
- trvae==1.0.1
- scanpy==1.5.1
- anndata==0.7.4 
- umap==0.4.4
- numpy==1.18.5
- scipy==1.4.1
- pandas==1.1.0
- scikit-learn==0.23.1
- statsmodels==0.11.1
- python-igraph==0.8.2
- louvain==0.7.0

Thanks for the help.

**Comment by M0hammadL** [comment]
dear @gauravj49, thanks a lot for posting this, we refactored the whole code. could you please install the latest
the version of the repo or pip and follow [this](https://nbviewer.jupyter.org/github/theislab/trVAE/blob/master/examples/trVAE_Haber.ipynb) tutorial.

**Comment by gauravj49** [comment]
Thank you @M0hammadL . I was able to make it work successfully.
